# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 08:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20170315_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterField(
            model_name='answer',
            name='added_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='added_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(related_name='q_to_l', to=settings.AUTH_USER_MODEL),
        ),
    ]
